### ISSUE TITLE
PHP 8?

### ISSUE THREAD

**Issue by iandoug** [xird/gd-heatmap#1]
Hi

Version specific?

PHP Warning:  Undefined property: gd_gradient_alpha::$image in /home/ian/projects/gd-heatmap-master/gd-rg.php on line 48
PHP Fatal error:  Uncaught TypeError: imagealphablending(): Argument #1 ($image) must be of type GdImage, null given in /home/ian/projects/gd-heatmap-master/gd_heatmap.php:113
Stack trace:
#0 /home/ian/projects/gd-heatmap-master/gd_heatmap.php(113): imagealphablending()
#1 /home/ian/projects/gd-heatmap-master/gd_heatmap.php(65): gd_heatmap->generate_image()
#2 /home/ian/projects/gd-heatmap-master/test.php(22): gd_heatmap->__construct()
#3 {main}
  thrown in /home/ian/projects/gd-heatmap-master/gd_heatmap.php on line 113

**Comment by xird** [comment]
Oh wow, this is a blast from the past. :smile: 

I haven't worked with PHP in years, so I'm afraid I have no idea about PHP 8 compatibility. If you can come up with a PR that fixes the issue, I'd be happy to merge it. Or even give ownership of the whole repo, if you're up for it.

**Comment by iandoug** [comment]
I looked at your code and did not know what/how to fix it ... I don't normally work in the object-orientated way of doing things.

Will tackle my needs in a different way, thanks.
